# Generated by Django 4.0.2 on 2022-02-06 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
